request: &request
  user_agent: "Mozilla/5.0 (Windows NT 10.0; rv:112.0) Gecko/20100101 Firefox/112.0"

global: &global # The message displayed on the index page of Inertia
  motd: "Inertia is a stylish, privacy-respecting meta-search engine for the modern web."

  # * Host options -->
  host:
    # The protocol used.
    # Accepted options: http, https
    protocol: "http"

    # The domain name or IP address of your server.
    # e.g. "inertia-search.xyz", "127.0.0.1:3000"
    hostname: "127.0.0.1:3000"

  # * Global search options -->
  search:
    # The default engine for text searches.
    # Accepted options: google
    default_text_engine: "google"

    # The default engine for image searches.
    # Accepted options: qwant; bing
    default_image_engine: "qwant"

  # * Google related options -->
  google:
    <<: *request

    # The TLD to use for requests made towards Google.
    # e.g. 'com' => google.com
    tld: "com"

  # * Qwant related options -->
  qwant:
    <<: *request

  # * Bing related options -->
  bing:
    <<: *request

  # * Wikipedia related options -->
  wikipedia:
    <<: *request

    # The language of Wikipedia.
    # This is used to filter searchr results and display summaries.
    # e.g. 'en' => en.wikipedia.org
    language: "en"

# Needed for Rails to correctly parse the config :p
production:
  <<: *request
  <<: *global

development:
  <<: *request
  <<: *global
